{
  imports = [
    #./nushell.nix
    ./zellij.nix
    ./fuzzel.nix
    #./zsh.nix
    ./firefox.nix
    ./lazygit.nix
    ./mako.nix
    ./fish.nix
    ./git.nix
    ./gtk.nix
    ./starship.nix
    #./sway.nix
    ./tmux.nix
    ./niri
    ./waybar
    ./yambar.nix
    ./helix
    ./foot.nix
    ./emacs/default.nix
    ./nyxt/default.nix
    ./wezterm/default.nix
    ./jujutsu.nix
    ./yazi.nix
  ];
}
