;; evil.el --- Not really evil, meow -*- no-byte-compile: t; lexical-binding: t; -*-

;; Prefix maps for meow leader
(define-prefix-command 'detached-prefix-map)
(dolist (binding '(("v" . detached-view-session)
                   ("a" . detached-attach-session)
                   ("=" . detached-diff-session)
                   ("S" . detached-shell-command)
                   ("s" . kristian/detached-run-command-git-root)
                   ("p" . kristian/detached-run-command-git-root-with-path)
                   ("c" . detached-compile-session)
                   ("r" . detached-rerun-session)
                   ("i" . detached-insert-session-command)
                   ("w" . detached-copy-session-command)
                   ("W" . detached-copy-session-output)
                   ("k" . detached-kill-session)
                   ("d" . detached-delete-session)
                   ))
  (define-key detached-prefix-map (kbd (car binding)) (cdr binding)))

(define-prefix-command 'meow-prefix-p-map)
(dolist (binding '(("s" . tabspaces-switch-or-create-workspace)
                   ("d" . tabspaces-close-workspace)
                   ("o" . tabspaces-open-or-create-project-and-workspace)
                   ("f" . project-find-file)))
  (define-key meow-prefix-p-map (kbd (car binding)) (cdr binding)))

(define-prefix-command 'meow-prefix-git)
(dolist (binding '(
                   ("r" . git-gutter:revert-hunk)
                   ("s" . git-gutter:stage-hunk)
                   ("p" . git-gutter:previous-hunk)
                   ("n" . git-gutter:next-hunk)
                   ("b" . magit-blame)
                   ))
  (define-key meow-prefix-git (kbd (car binding)) (cdr binding)))

(define-prefix-command 'meow-prefix-find)
(dolist (binding '(("g" . consult-ripgrep)
                   ("f" . consult-find)
                   ("l" . consult-line)
                   ("L" . kristian/consult-grep-line-from-visual-selection)
                   ("v" . kristian/consult-ripgrep-from-visual-selection)))
  (define-key meow-prefix-find (kbd (car binding)) (cdr binding)))

(define-prefix-command 'meow-prefix-t-map)
(dolist (binding '(("p" . eat-project-other-window)
                   ("n" . eat)
                   ("b" . kristian/consult-grep-project-buffer-term)
                   ("c" . kristian/my-toggle-theme)))
  (define-key meow-prefix-t-map (kbd (car binding)) (cdr binding)))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-colemak-dh)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '(";" . meow-comment)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)
   '("b" . consult-project-buffer)
   '("p" . meow-prefix-p-map)
   '("t" . meow-prefix-t-map)
   '("f" . meow-prefix-find)
   '("d" . meow-prefix-git)
   '("o" . dirvish-dwim)
   '("w" . save-buffer)
   '("r" . query-replace-regexp)
   '("s" . detached-prefix-map)
   )
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("/" . meow-visit)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("e" . meow-prev)
   '("E" . meow-prev-expand)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("m" . meow-left)
   '("M" . meow-left-expand)
   '("i" . meow-right)
   '("I" . meow-right-expand)
   '("j" . meow-join)
   '("k" . meow-kill)
   '("l" . meow-line)
   '("L" . meow-goto-line)
   '("h" . meow-mark-word)
   '("H" . meow-mark-symbol)
   '("n" . meow-next)
   '("N" . meow-next-expand)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("r" . meow-replace)
   '("s" . meow-insert)
   '("S" . meow-open-above)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-search)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   '("x" . meow-delete)
   '("X" . meow-backward-delete)
   '("y" . meow-save)
   '("d" . meow-pop-to-mark)
   '("D" . meow-unpop-to-mark)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :custom
                                        ;(meow-use-cursor-position-hack t)
  (meow-use-clipboard t)
  (meow-goto-line-function 'consult-goto-line)
  :config
  ;; set colors in theme
  (setq meow-use-dynamic-face-color nil)
  ;; Make sure delete char means delete char
  ;; see https://github.com/meow-edit/meow/issues/112
  (setq meow--kbd-delete-char "<deletechar>")
  (add-to-list 'meow-mode-state-list '(eshell-mode . insert))
  (add-to-list 'meow-mode-state-list '(eat-mode . insert))
  ;; start helpful in normal
  ;; (add-to-list 'meow-mode-state-list '(helpful-mode . normal))
  (meow-global-mode 1)
  (meow-setup))
